[workspace]
resolver = "2"

members = [
  "bin/integration-tests",
  "bin/miden-bench",
  "bin/miden-cli",
  "crates/idxdb-store",
  "crates/rust-client",
  "crates/sqlite-store",
  "crates/testing/miden-client-tests",
  "crates/testing/node-builder",
  "crates/testing/prover",
  "crates/web-client",
]

default-members = ["bin/miden-cli", "crates/rust-client"]

[workspace.package]
authors      = ["miden contributors"]
edition      = "2024"
license      = "MIT"
repository   = "https://github.com/0xMiden/miden-client"
rust-version = "1.90"
version      = "0.14.0"

[profile.test-dev]
inherits  = "dev"
opt-level = 1

[workspace.dependencies]
# Workspace crates
idxdb-store               = { default-features = false, package = "miden-idxdb-store", path = "crates/idxdb-store", version = "0.14" }
miden-client              = { default-features = false, path = "crates/rust-client", version = "0.14" }
miden-client-sqlite-store = { default-features = false, path = "crates/sqlite-store", version = "0.14" }

# Miden protocol dependencies
miden-protocol  = { branch = "next", default-features = false, git = "https://github.com/0xMiden/miden-base" }
miden-standards = { branch = "next", default-features = false, git = "https://github.com/0xMiden/miden-base" }
miden-testing   = { branch = "next", default-features = false, git = "https://github.com/0xMiden/miden-base" }
miden-tx        = { branch = "next", default-features = false, git = "https://github.com/0xMiden/miden-base" }

# Miden node dependencies
miden-node-block-producer = { branch = "next", git = "https://github.com/0xMiden/miden-node" }
miden-node-ntx-builder = { branch = "next", git = "https://github.com/0xMiden/miden-node" }
miden-node-proto-build = { branch = "next", default-features = false, git = "https://github.com/0xMiden/miden-node" }
miden-node-rpc = { branch = "next", git = "https://github.com/0xMiden/miden-node" }
miden-node-store = { branch = "next", git = "https://github.com/0xMiden/miden-node" }
miden-node-utils = { branch = "next", git = "https://github.com/0xMiden/miden-node" }
miden-node-validator = { branch = "next", git = "https://github.com/0xMiden/miden-node" }
miden-note-transport-proto-build = { default-features = false, version = "0.2" }
miden-remote-prover = { branch = "next", features = ["concurrent"], git = "https://github.com/0xMiden/miden-node" }
miden-remote-prover-client = { branch = "next", default-features = false, features = [
  "tx-prover",
], git = "https://github.com/0xMiden/miden-node" }

# Miden debug dependencies
miden-debug = { default-features = false, features = ["dap", "std"], path = "../miden-debug" }

# External dependencies
anyhow      = { default-features = false, version = "1.0" }
async-trait = { version = "0.1" }
chrono      = { version = "0.4" }
hex         = { version = "0.4" }
miette      = { features = ["fancy"], version = "7.6" }
rand        = { version = "0.9" }
serde       = { features = ["derive"], version = "1.0" }
thiserror   = { default-features = false, version = "2.0" }
tokio       = { features = ["macros", "rt-multi-thread"], version = "1.48" }
tracing     = { version = "0.1" }

# Lints are set to warn for development, which are promoted to errors in CI.
[workspace.lints.clippy]
# Pedantic lints are set to a lower priority which allows lints in the group to be selectively enabled.
pedantic = { level = "warn", priority = -1 }
# cast_possible_truncation =   "allow"  # Overly many instances especially regarding indices.
ignored_unit_patterns       = "allow" # Stylistic choice.
missing_errors_doc          = "allow" # TODO: fixup and enable this.
missing_panics_doc          = "allow" # TODO: fixup and enable this.
module_name_repetitions     = "allow" # Many triggers, and is a stylistic choice.
must_use_candidate          = "allow" # This marks many fn's which isn't helpful.
should_panic_without_expect = "allow" # We don't care about the specific panic message.
# End of pedantic lints.

# Patch to use local miden-vm, miden-base, and miden-node
[patch.crates-io]
miden-air = { path = "../miden-vm/air" }
miden-assembly = { path = "../miden-vm/crates/assembly" }
miden-assembly-syntax = { path = "../miden-vm/crates/assembly-syntax" }
miden-core = { path = "../miden-vm/core" }
miden-core-lib = { path = "../miden-vm/crates/lib/core" }
miden-debug-types = { path = "../miden-vm/crates/debug-types" }
miden-mast-package = { path = "../miden-vm/crates/mast-package" }
miden-processor = { path = "../miden-vm/processor" }
miden-prover = { path = "../miden-vm/prover" }
miden-utils-sync = { path = "../miden-vm/crates/utils-sync" }
miden-verifier = { path = "../miden-vm/verifier" }

[patch."https://github.com/0xMiden/miden-base.git"]
miden-agglayer = { path = "../miden-base/crates/miden-agglayer" }
miden-block-prover = { path = "../miden-base/crates/miden-block-prover" }
miden-protocol = { path = "../miden-base/crates/miden-protocol" }
miden-standards = { path = "../miden-base/crates/miden-standards" }
miden-testing = { path = "../miden-base/crates/miden-testing" }
miden-tx = { path = "../miden-base/crates/miden-tx" }
miden-tx-batch-prover = { path = "../miden-base/crates/miden-tx-batch-prover" }

[patch."https://github.com/0xMiden/miden-node.git"]
miden-node-block-producer = { path = "../miden-node/crates/block-producer" }
miden-node-ntx-builder = { path = "../miden-node/crates/ntx-builder" }
miden-node-proto-build = { path = "../miden-node/proto" }
miden-node-rpc = { path = "../miden-node/crates/rpc" }
miden-node-store = { path = "../miden-node/crates/store" }
miden-node-utils = { path = "../miden-node/crates/utils" }
miden-node-validator = { path = "../miden-node/crates/validator" }
miden-remote-prover = { path = "../miden-node/bin/remote-prover" }
miden-remote-prover-client = { path = "../miden-node/crates/remote-prover-client" }
